# Generated by Django 3.0.3 on 2020-02-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='我的博客的标题', max_length=50)),
                ('date', models.DateField()),
                ('imag', models.ImageField(default='default.png', upload_to='images/')),
                ('text', models.TextField(default='博客正文')),
            ],
        ),
    ]
